# ~/.tmux.conf
set -g @plugin 'catppuccin/tmux#v2.1.3'

# Options to make tmux more pleasant
set -g status-interval 2
set -sg escape-time 0
set -g mouse on
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
set -ag terminal-overrides ",xterm-256color:Tc"
unbind C-b
set-option -g prefix C-f
bind-key C-f send-prefix
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -in -selection clipboard" # Use "xclip -in -selection clipboard" for Linux
set -g allow-passthrough on
set -s set-clipboard on
setw -g mode-keys vi
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-and-cancel

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "basic"
set -g history-limit 500000


# Load catppuccin
run ~/.tmux/plugins/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""

# 1. Standard Catppuccin Modules
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_user}"

# 2. CPU Module
set -agF status-right "#{E:@catppuccin_status_cpu}"

# 3. Custom RAM Module (Powered by tmux-cpu)
# Matches the basic style: [Background Icon] [Surface0 Text]
set -ag status-right "#[fg=#{@thm_teal},bg=default]#[fg=#{@thm_crust},bg=#{@thm_teal}] #[fg=#{@thm_fg},bg=#{@thm_surface_0}] #{ram_percentage} #[bg=default]"
# 4. Custom Disk I/O Module (Powered by our script)
set -ag status-right "#[fg=#{@thm_mauve},bg=default]#[fg=#{@thm_crust},bg=#{@thm_mauve}]󰋊 #[fg=#{@thm_fg},bg=#{@thm_surface_0}] #(~/.tmux/scripts/io_usage.sh) #[bg=default]"
# 5. Uptime Module
set -ag status-right "#{E:@catppuccin_status_uptime}"

# Or, if using TPM, just run TPM
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore on

run '~/.tmux/plugins/tpm/tpm'

set -g status-bg default
set -g status-style bg=default
run '~/.tmux/plugins/tmux-resurrect/resurrect.tmux'
run '~/.tmux/plugins/tmux-continuum/continuum.tmux'

