# ~/.tmux.conf
set -g @plugin 'catppuccin/tmux#v2.1.3'
# Options to make tmux more pleasant
set -g status-interval 2
set -sg escape-time 5
set -g mouse on
set -g default-terminal "tmux-256color"
unbind C-b
set-option -g prefix C-f
set -g history-limit 50000
# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "basic"

# Load catppuccin
run ~/.tmux/plugins/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 200
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_user}"
set -agF status-right "#{E:@catppuccin_status_cpu}"

set -ag status-right "#[fg=#{@thm_peach},bg=default]#[fg=#{@thm_crust},bg=#{@thm_peach}] #[fg=#{@thm_fg},bg=#{@thm_surface_0}] #{ram_percentage} #[bg=default]"

# --- ADD THIS NEW GPU MODULE ---
# Custom GPU Module (Powered by our script)
# Matches the basic style. Uses a Peach color and an expansion card/GPU icon.
set -ag status-right "#(~/.tmux/scripts/gpu_usage.sh)"

# 4. Custom Disk I/O Module (Powered by our script)
set -ag status-right "#(~/.tmux/scripts/io_usage.sh)"
set -agF status-right "#{E:@catppuccin_status_battery}"

# Or, if using TPM, just run TPM
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
run '~/.tmux/plugins/tpm/tpm'
set -g status-bg default
set -g status-style bg=default

